// import { Inter } from "next/font/google";
import Link from 'next/link';
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next js Web-demy Beginner",
  description: "Generated by BlueCrown Båmi",
};

export default function RootLayout({ children }) {
  return (
    // <html lang="en">
    <html>
      <body>
      {/* <body className={inter.className}>{children}</body> */}
      <h1><a href="/">WEB-demy</a></h1>
      <ol>
        <li><Link href="/read/1">HTML5</Link></li>
        <li><Link href="/read/2">CSS</Link></li>
        <li><Link href="/read/3">JS</Link></li>
      </ol>
      {children}
      <ul>
        <li><Link href="/create">Create</Link></li>
        <li><Link href="/update/1">Update</Link></li>
        <li><input type="button" value="Delete"/></li>
      </ul>
      </body>
    </html>
  );
}
